services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8024:8000"
    volumes:
      - ./backend:/app
    environment:
      # Для тестирования используем захват вебкамеры из Windows по ZMQ
      - CAMERA_MODE=zmq
      # Когда запустишь capture-service на Windows, поменяй CAMERA_MODE=zmq
      # host.docker.internal позволяет из Docker (WSL) достучаться до хостовой Windows
      - ZMQ_CAMERA_ADDRESS=tcp://host.docker.internal:5555
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/webhmi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webhmi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  db_data:
